version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/caalberts/localroast
    steps:
      - checkout
      - run: make setup
      - run: make all